-- MySQL Script generated by MySQL Workbench
-- Sun Nov 10 15:59:10 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema proyecto_ip
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto_ip` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `proyecto_ip` ;

-- -----------------------------------------------------
-- Table `proyecto_ip`.`contacto_emergencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_ip`.`contacto_emergencia` (
  `contacto_id` INT NOT NULL,
  `paciente_id` INT NULL DEFAULT NULL,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `apellido` VARCHAR(255) NULL DEFAULT NULL,
  `parentesco` ENUM('Padre', 'Madre', 'Hermano', 'Hermana', 'Otro') NULL DEFAULT NULL,
  `direccion` VARCHAR(255) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`contacto_id`),
  INDEX `paciente_id` (`paciente_id` ASC) VISIBLE,
  CONSTRAINT `contacto_emergencia_ibfk_1`
    FOREIGN KEY (`paciente_id`)
    REFERENCES `proyecto_ip`.`paciente` (`paciente_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto_ip`.`dispositivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_ip`.`dispositivo` (
  `dispositivo_id` INT NOT NULL,
  `modelo` VARCHAR(255) NULL DEFAULT NULL,
  `fecha_fabricacion` DATETIME NULL DEFAULT NULL,
  `fecha_colocacion` DATETIME NULL DEFAULT NULL,
  `paciente_id` INT NULL DEFAULT NULL,
  `fabricante` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`dispositivo_id`),
  INDEX `paciente_id` (`paciente_id` ASC) VISIBLE,
  CONSTRAINT `dispositivo_ibfk_1`
    FOREIGN KEY (`paciente_id`)
    REFERENCES `proyecto_ip`.`paciente` (`paciente_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto_ip`.`historial_medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_ip`.`historial_medico` (
  `historial_id` INT NOT NULL,
  `diagnostico` TEXT NULL DEFAULT NULL,
  `tratamiento` TEXT NULL DEFAULT NULL,
  `notas` TEXT NULL DEFAULT NULL,
  `paciente_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`historial_id`),
  INDEX `paciente_id` (`paciente_id` ASC) VISIBLE,
  CONSTRAINT `historial_medico_ibfk_1`
    FOREIGN KEY (`paciente_id`)
    REFERENCES `proyecto_ip`.`paciente` (`paciente_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto_ip`.`medicion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_ip`.`medicion` (
  `medicion_id` INT NOT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  `glucemia` DECIMAL(10,2) NULL DEFAULT NULL,
  `fabricante` VARCHAR(255) NULL DEFAULT NULL,
  `dispositivo_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`medicion_id`),
  INDEX `dispositivo_id` (`dispositivo_id` ASC) VISIBLE,
  CONSTRAINT `medicion_ibfk_1`
    FOREIGN KEY (`dispositivo_id`)
    REFERENCES `proyecto_ip`.`dispositivo` (`dispositivo_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `proyecto_ip`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_ip`.`paciente` (
  `paciente_id` INT NOT NULL,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `apellido` VARCHAR(255) NULL DEFAULT NULL,
  `fecha_nacimiento` DATE NULL DEFAULT NULL,
  `sexo` ENUM('M', 'F') NULL DEFAULT NULL,
  `direccion` VARCHAR(255) NULL DEFAULT NULL,
  `peso` DECIMAL(5,2) NULL DEFAULT NULL,
  `altura` DECIMAL(5,2) NULL DEFAULT NULL,
  `correo` VARCHAR(255) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`paciente_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
